const ambientes = [
    {
        "id": 1,
        "nome": "L1 - Antesala Congeladores",
        "tipoAmbiente": "Climatização",
        "temperaturaReferencia": 14,
        "largura": 10,
        "altura": 7,
        "comprimento": 9.5,
        "fatorAmbiente": 55,
        "massaProduto": 0,
        "tempoProcesso": 0,
        "cargaTermica": 36575,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 8
    },
    {
        "id": 2,
        "nome": "L1 - Embalagem Secundária",
        "tipoAmbiente": "Antecâmara",
        "temperaturaReferencia": 12,
        "largura": 11,
        "altura": 7,
        "comprimento": 11,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 46585,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": -2
    },
    {
        "id": 3,
        "nome": "L1 - Lavanderia",
        "tipoAmbiente": "Climatização",
        "temperaturaReferencia": 12,
        "largura": 7.1,
        "altura": 7,
        "comprimento": 7.2,
        "fatorAmbiente": 55,
        "massaProduto": 0,
        "tempoProcesso": 21,
        "cargaTermica": 19681.2,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 9
    },
    {
        "id": 4,
        "nome": "L1 - Sala Chillers",
        "tipoAmbiente": "Climatização",
        "temperaturaReferencia": 12,
        "largura": 26,
        "altura": 7,
        "comprimento": 26,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 260260,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 3
    },
    {
        "id": 5,
        "nome": "L1 - Sala Congelador Placas",
        "tipoAmbiente": "Sala_cortes",
        "temperaturaReferencia": 12,
        "largura": 11.4,
        "altura": 7,
        "comprimento": 11.4,
        "fatorAmbiente": 60,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 54583.195,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 8
    },
    {
        "id": 6,
        "nome": "L1 - Sala de Cortes",
        "tipoAmbiente": "Sala_cortes",
        "temperaturaReferencia": 12,
        "largura": 37.5,
        "altura": 7,
        "comprimento": 37.5,
        "fatorAmbiente": 60,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 590625,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": -1
    },
    {
        "id": 7,
        "nome": "L1 - Sala de Painéis",
        "tipoAmbiente": "Climatização",
        "temperaturaReferencia": 12,
        "largura": 19,
        "altura": 7,
        "comprimento": 19,
        "fatorAmbiente": 55,
        "massaProduto": 0,
        "tempoProcesso": 21,
        "cargaTermica": 138985,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 10
    },
    {
        "id": 8,
        "nome": "L1 - Sala Pendura",
        "tipoAmbiente": "Climatização",
        "temperaturaReferencia": 12,
        "largura": 8,
        "altura": 7,
        "comprimento": 8,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 24640,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 4
    },
    {
        "id": 9,
        "nome": "L1 - Sala Robo",
        "tipoAmbiente": "Climatização",
        "temperaturaReferencia": 12,
        "largura": 7.8,
        "altura": 7,
        "comprimento": 7.7,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 23123.102,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": -2
    },
    {
        "id": 10,
        "nome": "L1 - Secundária Temperados",
        "tipoAmbiente": "Antecâmara",
        "temperaturaReferencia": 12,
        "largura": 7.8,
        "altura": 7,
        "comprimento": 7.7,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 23123.102,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 4
    },
    {
        "id": 11,
        "nome": "L1 - Temperados",
        "tipoAmbiente": "Climatização",
        "temperaturaReferencia": 12,
        "largura": 9.5,
        "altura": 7,
        "comprimento": 9.4,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 34380.5,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 10
    },
    {
        "id": 12,
        "nome": "L1 - URAs Cortes",
        "tipoAmbiente": "Antecâmara",
        "temperaturaReferencia": 12,
        "largura": 34.4,
        "altura": 7,
        "comprimento": 34.3,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 454269.22,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 15
    },
    {
        "id": 13,
        "nome": "L2 - Antesala Giro",
        "tipoAmbiente": "Climatização",
        "temperaturaReferencia": 12,
        "largura": 7.6,
        "altura": 7,
        "comprimento": 7.5,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 21945,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": 15
    },
    {
        "id": 14,
        "nome": "L2 - Antesala Túnel",
        "tipoAmbiente": "Antecâmara",
        "temperaturaReferencia": 12,
        "largura": 6.9,
        "altura": 7,
        "comprimento": 6.8,
        "fatorAmbiente": 55,
        "massaProduto": 1,
        "tempoProcesso": 24,
        "cargaTermica": 18064.2,
        "ativo": true,
        "regimeId": 2,
        "evaporadores": [],
        "temperaturaAtual": -1
    }
];

module.exports = {
    ambientes
};